### ISSUE TITLE
MultilingualField and MultilingualCharField

### ISSUE THREAD

**Issue by IdemenB** [PacktPublishing/Django-3-Web-Development-Cookbook-Fourth-Edition#15]
Hi,

Implementing MultilingualField and MultilingualCharField as abstract base classes and using them as mixins for various models is really very useful, thank you very much for this insight in the book. Yet, a small trick would be even more fruitful; right now is there the default language set in the settings is "en", and if there are two languages of application defined as "en" and "de" and if we name the model field as "title", what the method does is producing "title_en" and "title_de" fields into the DB. Instead, if we create only the marginal languages on top of the default one, it will be super helpful in many places throughout the application. What I mean is the following:

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("de", "German"),

Model field name = "title"

-> Create the following fields in the DB: "title" and "title_de". No, "title_en" as it is the name given for the primary language anyway.

Unfortunately I've found the relevant django classes used in the book very complicated and could not do this by myself.

**Comment by archatas** [comment]
Hi, @IdemenB! Thanks for the comment.

In my opinion, no language is superior against other languages and it should be easy to switch the default language if necessary. For example, in Germany, the German language would be the default, but English is a "marginal" language.

Moreover, "title" is set as a property and it returns the title in the currently active language.

**Comment by IdemenB** [comment]
Thank you very much @archatas ! i am sorry if I was misunderstood, of course i did not mean a language is superior. By marginal what i mean is what comes on top of the language day is set as default in the settings.

When I use the code in the book and use MultilingualField for a model field, it creates "{fieldname}_langcode" fields for all languages, including the default one. So, if i refer to the field like "self.title" in the str method of the model, it can't find it and but self.title_en works (assuming en is the default language).

**Comment by archatas** [comment]
The code works so that if you read the "{fieldname}", it will return the value of "{fieldname}_langcode" of the language that is currently selected by the visitor of the website. If that value is empty, then the value of "{fieldname}_defaultlangcode" will be returned. All that is implemented by this function that you can find in the code:

```
        def translated_value(self):
            language = get_language()
            val = self.__dict__.get(
                MultilingualField.localized_field_name(
                        name, language))
            if not val:
                val = self.__dict__.get(
                    MultilingualField.localized_field_name(
                            name, settings.LANGUAGE_CODE))
            return val

        # ...
        setattr(cls, name, property(translated_value))
```

**Comment by IdemenB** [comment]
Thank you for this guidance and the book very much!
