### ISSUE TITLE
ImportError: cannot import name 'six' from 'django.utils' when running ch03 code

### ISSUE THREAD

**Issue by blessedsibanda** [PacktPublishing/Django-3-Web-Development-Cookbook-Fourth-Edition#16]
Am running on Linux Ubuntu 18.04
Python version 3.8
Django==3.0.3 

I tried reinstalling and installing the correct versions for django-elasticsearch-dsl and django-haystack but the error still persists

**Comment by archatas** [comment]
At the moment I have no possibility to test the chapter's code on the Linux distribution you specified. But I can ensure that it was working at the time of writing the book.

Can you please paste the traceback, when you launch local development server with `--traceback` parameter? It should give more insights about where the problem occurs.
